import { Note } from "./App";

const defaultNotes: Note[] = [
  {
    title: 'RSA Notes',
    text: 'RSA (Rivest-Shamir-Adleman) is a public-key cryptosystem that is widely used for secure data transmission. It is also one of the oldest. The acronym "RSA" comes from the surnames of Ron Rivest, Adi Shamir and Leonard Adleman, who publicly described the algorithm in 1977. An equivalent system was developed secretly in 1973 at GCHQ (the British signals intelligence agency) by the English mathematician Clifford Cocks. That system was declassified in 1997. In a public-key cryptosystem, the encryption key is public and distinct from the decryption key, which is kept secret (private). An RSA user creates and publishes a public key based on two large prime numbers, along with an auxiliary value. The prime numbers are kept secret. Messages can be encrypted by anyone, via the public key, but can only be decoded by someone who knows the prime numbers. The security of RSA relies on the practical difficulty of factoring the product of two large prime numbers, the "factoring problem". Breaking RSA encryption is known as the RSA problem. Whether it is as difficult as the factoring problem is an open question.[3] There are no published methods to defeat the system if a large enough key is used. ',
    id: '1',
    tags: ['Computer Science', 'Cryptography'],
  },
  {
    title: 'Fast Transformers on CPUs',
    text: 'Most people are not very familiar with the concept of artificial intelligence (AI). As an illustration, when 1,500 senior business leaders in the United States in 2017 were asked about AI, only 17 percent said they were familiar with it.[1] A number of them were not sure what it was or how it would affect their particular companies. They understood there was considerable potential for altering business processes, but were not clear how AI could be deployed within their own organizations. Despite its widespread lack of familiarity, AI is a technology that is transforming every walk of life. It is a wide-ranging tool that enables people to rethink how we integrate information, analyze data, and use the resulting insights to improve decisionmaking. Our hope through this comprehensive overview is to explain AI to an audience of policymakers, opinion leaders, and interested observers, and demonstrate how AI already is altering the world and raising important questions for society, the economy, and governance. In this paper, we discuss novel applications in finance, national security, health care, criminal justice, transportation, and smart cities, and address issues such as data access problems, algorithmic bias, AI ethics and transparency, and legal liability for AI decisions. We contrast the regulatory approaches of the U.S. and European Union, and close by making a number of recommendations for getting the most out of AI while still protecting important human values.[2]',
    id: '2',
    tags: ['Artificial Intelligence', 'Computer Science'],
  },
  {
    title: 'Theory of Evolution',
    text: 'contemporaries believed that species were unchangeable, structures made due to will of the Divine Creator proposed that natural laws produced change/evolution over time never challenged the existence of a Divine Creator based his ideas on studies in S America and Galápagos Islands didn\'t publish his results for 16 years until Alfred Russel Wallace submitted similar theory independently The Descent of Man - argues that humans and apes have similar ancestors',
    id: '3',
    tags: ['Biology'],
  },
  {
    title: 'Organization of living things',
    text: 'Properties of Life: cellular organization - containing 1 or more cells, w/ basic life activities in each cell; cells are separated by a membra: order - many different types of cells, each w/ molecular structur: sensitivity - response to a stimulus (change in the environmen: growth, development, reproduction - ability to grow/reproduce, pass down hereditary materi: energy utilization - taking in energy to do wo: evolutionary adaptation - long-term response to things that affect surviv: homeostasis - maintaining constant internal conditio: hierarchical organization - each level builds on the level below it in biology: cellular level - atoms >> molecules >> macromolecules >> organelles >> ce: organismal level - tissue >> organ >> organ system >> organi: population level - population (group of same species living in one place) >> species (group of organisms able to interbreed) >> biological community >> ecosyst: emergent properties - results from how cells interact and work: cannot be determined just be looking at the cel: many creatures have the same type of cells, but appear/work different: deductive reasoning - uses general principles/rules to predict specific results: reasoning used in mathematics/philosop: used to test validity of general ide: inductive reasoning - uses specific observations to make general principles/rules: leads to generalizations that can be test: modern science uses specific observations to make general models, which are later test: scientific investigations - all begins w/ series of observations: hypothesis - suggested explanation that accounts for the observations; can be modified or replac: experiment - test of a hypothes: variable - factor possibly affecting the experime: control experiment - test where the variable is left unchang: differences in results between experiments are due to the variable chan: inconsistent results can lead to the hypothesis being reject: theory - either an explanation for natural phenomenon, or brings together many concepts once thought to be unrelat: basic research - done just to expand knowled: applied research - done as part of some industry or j: peer review - evaluation of any experiment to see if it\'s accurate:',
    id: '4',
    tags: ['Biology'],
  },
  {
    title: 'Diffie-Hellman Key Exchange',
    text: 'Diffie-Hellman key exchange[nb 1] is a method of securely exchanging cryptographic keys over a public channel and was one of the first public-key protocols as conceived by Ralph Merkle and named after Whitfield Diffie and Martin Hellman.[1][2] DH is one of the earliest practical examples of public key exchange implemented within the field of cryptography. Published in 1976 by Diffie and Hellman, this is the earliest publicly known work that proposed the idea of a private key and a corresponding public key. Traditionally, secure encrypted communication between two parties required that they first exchange keys by some secure physical means, such as paper key lists transported by a trusted courier. The Diffie-Hellman key exchange method allows two parties that have no prior knowledge of each other to jointly establish a shared secret key over an insecure channel. This key can then be used to encrypt subsequent communications using a symmetric-key cipher. Diffie-Hellman is used to secure a variety of Internet services. However, research published in October 2015 suggests that the parameters in use for many DH Internet applications at that time are not strong enough to prevent compromise by very well-funded attackers, such as the security services of some countries.[3] The scheme was published by Whitfield Diffie and Martin Hellman in 1976,[2] but in 1997 it was revealed that James H. Ellis,[4] Clifford Cocks, and Malcolm J. Williamson of GCHQ, the British signals intelligence agency, had previously shown in 1969[5] how public-key cryptography could be achieved.[6] Although Diffie-Hellman key agreement itself is a non-authenticated key-agreement protocol, it provides the basis for a variety of authenticated protocols, and is used to provide forward secrecy in Transport Layer Security\'s ephemeral modes (referred to as EDH or DHE depending on the cipher suite). The method was followed shortly afterwards by RSA, an implementation of public-key cryptography using asymmetric algorithms. Expired U.S. Patent 4,200,770 from 1977 describes the now public-domain algorithm. It credits Hellman, Diffie, and Merkle as inventors. ',
    id: '5',
    tags: ['Computer Science', 'Cryptography'],
  },
];
export default defaultNotes;